# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-21 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=225, verbose_name='Título')),
                ('descripcion', models.TextField(default='Inicio de descripcion: ')),
                ('estado', models.BooleanField(verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
            ],
        ),
    ]
