# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-21 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Título'),
        ),
    ]
