# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-22 05:32
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import estudiantes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombres', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=250)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=220)),
                ('foto', models.ImageField(null=True, upload_to=estudiantes.models.url, verbose_name='Imagen')),
                ('estado_civil', models.CharField(choices=[('s', 'Soltero(a)'), ('c', 'Casado(a)'), ('u', 'Union'), ('d', 'Divorsiad(a)'), ('v', 'Viudo(a)')], max_length=220, null=True)),
                ('fecha_nacimiento', models.DateField(auto_now_add=True)),
                ('facebook', models.CharField(blank=True, max_length=220, null=True)),
                ('direccion', models.CharField(blank=True, max_length=220, null=True)),
                ('telefono', models.CharField(blank=True, max_length=220, null=True)),
                ('es_admin', models.BooleanField(default=False)),
                ('estado', models.PositiveIntegerField(choices=[(0, 'Pendiente'), (1, 'Activo'), (2, 'Inactivado'), (3, 'Eliminado')], default=1)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_creacion', models.CharField(max_length=50)),
                ('usuario_actualizacion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
