# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-22 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_auto_20180422_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='sexo',
        ),
    ]
