# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-23 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import estudiantes.models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0007_auto_20180422_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiante',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='es_admin',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='estado',
            field=models.PositiveIntegerField(choices=[(0, 'Pendiente'), (1, 'Activo'), (2, 'Inactivado'), (3, 'Eliminado'), (4, 'Aprobado'), (5, 'Reprobado')], default=1),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='facebook',
            field=models.CharField(blank=True, help_text='Ingrese el nombre de su cuenta en fb', max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='foto',
            field=models.ImageField(null=True, upload_to=estudiantes.models.url, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombres',
            field=models.CharField(max_length=250, verbose_name='Nombres'),
        ),
    ]
